apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lib-bucket-provisioner-alpha-lib-bucket-catalogsource-openshift-marketplace
  namespace: openshift-storage
spec:
  channel: alpha
  config:
    resources: {}
  installPlanApproval: Automatic
  name: lib-bucket-provisioner
  source: lib-bucket-catalogsource
  sourceNamespace: openshift-marketplace
  startingCSV: lib-bucket-provisioner.v1.0.0
