apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  channel: stable-4.4
  installPlanApproval: Automatic
  name: ocs-operator
  source: my-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v4.4.1
